<div class="footer section-space20">
    <!-- footer -->
    <div class="container">
        <?php //echo $this->partial('layout/borrow/suscribe'); ?>

        <div class="row">
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="widget-text mt40">
                    <!-- widget text -->
                    <p>Our goal  is to provide ...</p>
                    <div class="row">
                        <div class="col-md-6 col-xs-6">
                            <p class="address-text"><span><i class="icon-placeholder-3 icon-1x"></i> </span>3895 Sycamore Road Arlington, 97812 </p>
                        </div>
                        <div class="col-md-6 col-xs-6">

                        </div>
                    </div>
                </div>
                <!-- /.widget text -->
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="widget-footer mt40">
                    <!-- widget footer -->
                    <ul class="listnone">
                        <li><a href="">Home</a></li>
                        <li><a href="">Services</a></li>
                        <li><a href="">About Us</a></li>
                        <li><a href="">News</a></li>
                        <li><a href="">Faq</a></li>
                        <li><a href="">Contact Us</a></li>
                    </ul>
                </div>
                <!-- /.widget footer -->
            </div>

            <div class="col-md-2 col-sm-4 col-xs-12">
                <div class="widget-social mt40">
                    <!-- widget footer -->
                    <ul class="listnone">
                        <li><a href="#"><i class="fa fa-facebook"></i>Facebook</a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i>Google Plus</a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i>Twitter</a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i>Linked In</a></li>
                    </ul>
                </div>
                <!-- /.widget footer -->
            </div>
        </div>
    </div>
</div>

<?php echo $this->partial('layout/borrow/tiny-footer'); ?>