<div class="tiny-footer">
    <!-- tiny footer -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <p>© Copyright 2017 | GET MARRIED IN ARGENTINA</p>
            </div>
            <div class="col-md-6 col-sm-6 text-right col-xs-6">
                <p><a>Terms of use | Privacy Policy </a></p>
            </div>
        </div>
    </div>
</div>