<div class="footer section-space20">
    <!-- footer -->
    <div class="container">
        <?php //echo $this->partial('layout/borrow/suscribe'); ?>

        <div class="row">

            <div class="col-md-2 col-sm-4 col-xs-12">
                <div class="widget-social mt40">
                    <ul class="listnone">
                        <li><a target="_blank" href="https://www.facebook.com/get.married.98478"><i class="fa fa-facebook"></i>Facebook</a></li>
                        <li><a target="_blank" href="https://www.instagram.com/getmarriedinargentina/"><i class="fa fa-instagram"></i>Instagram</a></li>
                    </ul>
                </div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-12">
                <div class="widget-social mt40">
                    <ul class="listnone">
                        <li><a target="_blank" href="https://twitter.com/getmarriedarg"><i class="fa fa-twitter"></i>Twitter</a></li>
                        <li><a target="_blank" href="https://ar.pinterest.com/GetMarriedinArgentina/"><i class="fa fa-pinterest"></i>Pinterest</a></li>
                    </ul>
                </div>

            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">

            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="widget-footer mt40">
                    <!-- widget footer -->
                    <ul class="listnone">
                        <li><a href="/#section_home"><?= $this->translate('Home') ?></a></li>
                        <li><a href="/#section_aboutus"><?= $this->translate('About Us') ?></a></li>

                    </ul>
                </div>
                <!-- /.widget footer -->
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="widget-footer mt40">
                    <!-- widget footer -->
                    <ul class="listnone">
                        <li><a href="/#section_services"><?= $this->translate('Services') ?></a></li>
                        <li><a href="/#section_contact"><?= $this->translate('Contact us') ?></a></li>
                    </ul>
                </div>
                <!-- /.widget footer -->
            </div>

        </div>
    </div>
</div>

<?php echo $this->partial('layout/borrow/tiny-footer'); ?>