<?php
$session = new \Zend\Session\Container('language');$session->language;
?>
<form action="/lang" method="post">
    <label class="mail-text text-center">Language</label>
    <select id="language" name="language">
        <option value="en" <?php if($session->language== "en"){ echo 'selected="selected"';} ?> >English</option>
        <option value="es" <?php if($session->language== "es"){ echo 'selected="selected"';} ?> >Spanish</option>
    </select>
</form>

<!-- /.top-bar -->

<script >
  $(function() {
    $("#language").change(function() {
      $("form").submit();
    });
  });
</script>