<div class="header-transparent navbar-fixed-top">
    <div class="container">
        <div class="row">
            <div class="pull-right">
                <?php echo $this->partial('layout/borrow/lang'); ?>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-6">
                <!-- logo -->
                <div class="logo">
                    <h3 class="slider-text text-center" href="">GetMarried<br>In Buenos Aires</h3>
                </div>
            </div>
            <!-- logo -->
            <div class="col-lg-6 col-md-8 col-sm-12 col-xs-12">
                <div id="navigation">
                    <ul>
                        <li class="active">
                            <a href="#section_home" class="animsition-link">Home</a>
                        </li>
                        <li>
                            <a href="#section_aboutus" class="animsition-link">About us</a>
                        </li>
                        <li>
                            <a href="#section_services" class="animsition-link">Services</a>
                        </li>
                        <li>
                            <a href="#section_contact" title="Contact us" class="animsition-link">Contact us</a>
                        </li>
                    </ul>
                </div>

            </div>

        </div>
    </div>
</div>

<script type="text/javascript">
  //jQuery to collapse the navbar on scroll
  $(window).scroll(function() {
    if ($(".header-transparent").offset().top > 50) {
      $(".navbar-fixed-top").addClass("top-nav-collapse");
    } else {
      $(".navbar-fixed-top").removeClass("top-nav-collapse");
    }
  });
</script>