<div class="header">
<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-12 col-xs-6">
            <!-- logo -->
            <div class="logo">
                <a href="index.html"><img src="img/getmarriedlogo.png" alt="Borrow - Loan Company Website Template"></a>
            </div>
        </div>
        <!-- logo -->
        <div class="col-md-9 col-sm-12 col-xs-12">
            <div id="navigation">
                <!-- navigation start-->
                <ul>
                    <li class="active"><a href="/#section_home" class="animsition-link">Home</a>
                    </li>
                    <li><a href="/#section_aboutus" class="animsition-link">About us</a>
                    </li>
                    <li><a href="/#section_services" class="animsition-link">Services</a>
                    </li>
                    <li><a href="/#section_contact" title="Contact us" class="animsition-link">Contact us</a>
                    </li>
                </ul>
            </div>
            <!-- /.navigation start-->
        </div>
    </div>
</div>
</div>