<div class="header">
<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-12 col-xs-6">
            <!-- logo -->
            <div class="logo">
                <a href="index.html"><img src="img/getmarriedlogo.png" alt="Borrow - Loan Company Website Template"></a>
            </div>
        </div>
        <!-- logo -->
        <div class="col-md-9 col-sm-12 col-xs-12">
            <div id="navigation">
                <!-- navigation start-->
                <ul>
                    <li class="active"><a href="/" class="animsition-link">Home</a>
                    </li>
                    <li><a href="/" class="animsition-link">Services</a>
                    </li>
                    <li><a href="/" class="animsition-link">About us</a>
                        <ul>
                            <li><a href="/" title="About us" class="animsition-link">About us</a></li>
                            <li><a href="/" title="Team" class="animsition-link">Team</a></li>
                        </ul>
                    </li>
                    <!--  <li><a href="blog-listing.html" class="animsition-link">Blog</a>
                      </li>-->

                    <li><a href="/" title="Contact us" class="animsition-link">Contact us</a></li>
                </ul>
            </div>
            <!-- /.navigation start-->
        </div>
    </div>
</div>
</div>