<div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="footer-logo">
            <!-- Footer Logo -->
            <h3 class="newsletter-title text-center">Get Married</h3>

        </div>
        <!-- /.Footer Logo -->
    </div>
    <div class="col-md-8 col-sm-8 col-xs-12">
        <div class="col-md-5">
            <h3 class="newsletter-title">Signup Our Newsletter</h3>
        </div>
        <div class="col-md-7">
            <div class="newsletter-form">
                <!-- Newsletter Form -->
                <form action="newsletter.php" method="post">
                    <div class="input-group">
                        <input type="email" class="form-control" id="newsletter" name="newsletter" placeholder="Write E-Mail Address" required="">
                        <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go!</button>
                </span> </div>
                    <!-- /input-group -->
                </form>
            </div>
            <!-- /.Newsletter Form -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
</div>
<hr class="dark-line">