<div class="top-bar">
    <!-- top-bar -->
    <div class="container">
        <div class="row">
            <div class="col-md-4 hidden-xs hidden-sm">
                <p class="mail-text">Welcome to Get Married in Argentina</p>
            </div>
            <div class="col-md-3 hidden-xs hidden-sm">
                <p class="mail-text text-center">Call us at 1-800-123-4567</p>
            </div>
            <div class="col-md-3 hidden-xs hidden-sm">
                <p class="mail-text text-center">Mon to fri 10:00am - 06:00pm</p>
            </div>
            <div class="col-md-2 hidden-xs hidden-sm">
                <p class="mail-text text-center">Get started today</p>
            </div>
        </div>
    </div>
</div>
<!-- /.top-bar -->