<div class="top-bar">
    <!-- top-bar -->
    <div class="container">
        <div class="row">
            <div class="col-md-3 hidden-xs hidden-sm">
                <p class="mail-text">Welcome to Get Married in Argentina</p>
            </div>
            <div class="col-md-3 hidden-xs hidden-sm">
                <p class="mail-text text-center">Call us at 1-800-123-4567</p>
            </div>
            <div class="col-md-3 hidden-xs hidden-sm">
                <p class="mail-text text-center">getmarried@gmail.com</p>
            </div>
            <div class="col-md-3 hidden-xs hidden-sm">
                <?php echo $this->partial('layout/borrow/lang'); ?>
            </div>
        </div>
    </div>
</div>
