<?= $this->partial('application/partial/slider'); ?>
<div class="container ">

    <div class="row">

        <div class="col-md-12">
            <div class=" bg-white">
                <div class="pinside20">
                    <div class="row">
                        <div class="col-md-6">
                            <img src="img/Portada.png" class="img-responsive"/>

                        </div>

                        <div class="col-md-6">
                            <p>There are manyreasons why you’d like to marry in Buenos Aires, Argentina. Sexual
                                orientation,
                                faith
                                or simply fun.
                                Whatever your reasons we can help you make your dream come true.</p>
                            <p>We offer assistance with all paperwork, translations and interpretation services required
                                for a
                                civil
                                ceremony in Buenos Aires.</p>
                            <p>Our country is not only a place for tango lovers but also a place where civil rights are
                                granted
                                to
                                everybody.</p>
                            <p>In Argentina same sex marriage is legal and, as stated in our Marriage Law, “any
                                foreigner
                                (regardless their sexual orientation) who enters, travels or resides in The Argentine
                                Republic”
                                can
                                marry.</p>
                            <p>Therefore, our country is one of the few places where everyone can legally marry and the
                                only
                                place
                                in the world where tourists can do so.</p>
                            <p>Want more information? Contact us!</p>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<br><br><br>
