<?php  echo $this->partial('application/partial/slider'); ?>
<div class="bg-white section-space80">
    <div class="container">
        <div class="row">

            <div class="col-md-12">
                <div class=" bg-white">
                    <div>
                        <div class="row">
                            <!--  <div class="col-md-6">
                                  <img src="img/Portada.png" class="img-responsive"/>

                              </div>-->

                            <div class="col-md-10 col-md-offset-2">
                                <h1><?= $this->translate("Get Married") ?></h1>
                                <p>
                                    <?= $this->translate("Why would you choose Buenos Aires to marry?") ?>
                                </p>
                                <p>
                                    <?= $this->translate("There are many reasons why you’d like to marry in Buenos Aires, Argentina. Sexual orientation, faith or simply fun. Whatever your reasons we can help you make your dream come true") ?>
                                    .
                                </p>
                                <p>
                                    <?= $this->translate("We offer assistance with all paperwork, translations and interpretation services required for a civil ceremony in Buenos Aires.") ?>
                                </p>
                                <p>
                                    <?= $this->translate("Our country is not only a place for tango lovers but also a place where civil rights are granted to everybody.") ?>
                                </p>
                                <p>
                                    <?= $this->translate("In Argentina same sex marriage is legal and, as stated in our Marriage Law, “any foreigner (regardless their sexual orientation) who enters, travels or resides in The Argentine Republic” can marry") ?>
                                    .
                                </p>
                                <p>
                                    <?= $this->translate("Therefore, our country is one of the few places where everyone can legally marry and the only place in the world where tourists can do so.") ?>
                                </p>
                                <p>
                                    <?= $this->translate("Want more information? Contact us!") ?>
                                </p>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<br><br>
<div class="bg-white section-space80">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8 col-xs-12">
                <div class="mb100 text-left section-title">
                    <!-- section title start-->
                    <h1> <?= $this->translate("WHAT WE OFFER") ?>:</h1>
                    <p><?= $this->translate("You don’t need to know how to speak Spanish or how to deal with the paperwork in Argentine institutions such as the Civil Registry. We do that for you only for USD 2,000.") ?></p>
                    <ul>
                        <li>Hotel booking</li>
                        <li>Transport from and to the airport (and within Buenos Aires)</li>
                        <li>Assistance with all paperwork</li>
                        <li>Civil wedding</li>
                        <li>A dinner last night to celebrate!</li>
                    </ul>
                </div>
                <!-- /.section title start-->
            </div>
        </div>

    </div>
</div>
<br><br>
<div class="bg-white section-space80">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8 col-xs-12">
                <div class="mb100 text-center section-title">
                    <!-- section title start-->
                    <h1>How does it work?</h1>
                    <p>We have a fast and easy process.</p>
                </div>
                <!-- /.section title start-->
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="bg-white pinside40 number-block mb30 outline">
                    <div class="circle"><span class="number">1</span></div>
                    <h3>Choose Loan Amount</h3>
                    <p>Suspendisse accumsan imperdue ligula dignissim sit amet vestibulum in mollis etfelis.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="bg-white pinside40 number-block mb30 outline">
                    <div class="circle"><span class="number">2</span></div>
                    <h3>Approved Your Loan</h3>
                    <p>Fusce tempor sstibulum varius sem nec mi luctus viverra edcongue lobortis faucibus.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="bg-white pinside40 number-block mb30 outline">
                    <div class="circle"><span class="number">3</span></div>
                    <h3>Get Your Cash</h3>
                    <p>Get your money in minutes simtibulm varius semnec mluctus gue lobortis faucibus.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8 text-center mt30"><a href="#"
                                                                                               class="btn btn-default">Find
                    your rate</a></div>
        </div>
    </div>
</div>
