<?php echo $this->partial('application/partial/slider'); ?>

<a name="section_aboutas"></a>
<div id="section_aboutus" class="bg-white section-space80">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class=" bg-white">
                    <div>
                        <div class="row">
                            <div class="col-md-8">
                                <h1><?= $this->translate("Get Married") ?></h1>
                                <p>
                                    <?= $this->translate("Why would you choose Buenos Aires to marry?") ?>
                                </p>
                                <p>
                                    <?= $this->translate("There are many reasons why you’d like to marry in Buenos Aires, Argentina. Sexual orientation, faith or simply fun. Whatever your reasons we can help you make your dream come true") ?>
                                    .
                                </p>
                                <p>
                                    <?= $this->translate("We offer assistance with all paperwork, translations and interpretation services required for a civil ceremony in Buenos Aires.") ?>
                                </p>
                                <p>
                                    <?= $this->translate("Our country is not only a place for tango lovers but also a place where civil rights are granted to everybody.") ?>
                                </p>
                                <p>
                                    <?= $this->translate("In Argentina same sex marriage is legal and, as stated in our Marriage Law, “any foreigner (regardless their sexual orientation) who enters, travels or resides in The Argentine Republic” can marry") ?>
                                    .
                                </p>
                                <p>
                                    <?= $this->translate("Therefore, our country is one of the few places where everyone can legally marry and the only place in the world where tourists can do so.") ?>
                                </p>
                                <p>
                                    <?= $this->translate("Want more information? Contact us!") ?>
                                </p>
                            </div>
                            <div class="col-md-4 text-center">
                                <br><br><br><br>
                                <img src="img/getmarriedlogo.png" class=" text-center "/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br>
<a name="section_services"></a>
<div id="section_services" class="bg-white section-space80">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8 col-xs-12">
                <div class="mb100 text-left section-title">
                    <h1> <?= $this->translate("WHAT WE OFFER") ?>:</h1>
                    <p><?= $this->translate("You don’t need to know how to speak Spanish or how to deal with the paperwork in Argentine institutions such as the Civil Registry. We do that for you only for USD 2,000.") ?></p>
                    <ul>
                        <li>Hotel booking</li>
                        <li>Transport from and to the airport (and within Buenos Aires)</li>
                        <li>Assistance with all paperwork</li>
                        <li>Civil wedding</li>
                        <li>A dinner last night to celebrate!</li>
                    </ul>
                </div>

            </div>
        </div>

    </div>
</div>
<br><br>
<a name="section_contact"></a>
<div id="section_contact" class="bg-white section-space80">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8 col-xs-12">
                <div class="mb100 text-left section-title">
                    <h1> <?= $this->translate("Contact") ?>:</h1>
                    <?php
                    $config = [
                        [
                            'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                            'id' => 'nombreApellido',
                            'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                            'style' => \ZfMetal\Commons\Consts::STYLE_PLACEHOLDER,
                            'fields' => ['name', 'lastname']
                        ],
                        [
                            'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                            'id' => 'email',
                            'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                            'style' => \ZfMetal\Commons\Consts::STYLE_PLACEHOLDER,
                            'fields' => ['email']
                        ],
                        [
                            'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                            'id' => 'message',
                            'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                            'style' => \ZfMetal\Commons\Consts::STYLE_PLACEHOLDER,
                            'fields' => ['message']
                        ]
                    ];
                    echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_PLACEHOLDER, \ZfMetal\Commons\Consts::COLUMNS_TWO, $config);
                    ?>
                </div>

            </div>
        </div>

    </div>
</div>
<br>